### ISSUE TITLE
Docker Componse setup

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-docker#2]
Create a multi-container Crossbar.io demo with 1 router, and 3 Autobahn containers specified as a Docker compose thing.

**Comment by agronholm** [comment]
Here's something to get you started:
```yaml
version: "2"
services:
  crossbar:
    image: crossbario/crossbar
    ports:
      - "8080:8080"

  app1:
    build: ./app1
    links:
      - crossbar

  app2:
    build: ./app2
    links:
      - crossbar

  app3:
    build: ./app3
    links:
      - crossbar
```
